name: app_enfermeria
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.8.1 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    video_player: ^2.8.1
    video_player_web: ^2.0.16
    cupertino_icons: ^1.0.8
    table_calendar: ^3.0.9
    cloud_firestore: ^5.6.8
    firebase_core: ^3.13.1
    firebase_auth: ^5.5.4
    url_launcher: ^6.1.11
    webview_flutter: ^4.4.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/avatar/
        - assets/agua.png
        - assets/logo.png
        - assets/logo2.png
